version: "3"
services:
  plugin:
    build: .
    environment:
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_SERVER
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_TOKEN
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_IMAGE
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_POLICY
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_LABELS
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_SCAN_ID
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_INTERVAL
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_RETRIES
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_GOKAKASHI_VERSION
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_CF_CLIENT_ID
      - BUILDKITE_PLUGIN_GOKAKASHI_BUILDKITE_CF_CLIENT_SECRET
      - BUILDKITE_AGENT_META_DATA_PATH=/tmp/buildkite-agent/meta-data

  lint:
    image: buildkite/plugin-linter
    command: ["--id", "hasura/gokakashi"]
    volumes:
      - .:/plugin:ro

  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin:ro
