version: '3'
services:
  plugin:
    build: .
    environment:
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_SERVER
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_TOKEN
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_IMAGE
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_POLICY
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_LABELS
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_SCAN_ID
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_INTERVAL
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_RETRIES
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_GOKAKASHI_VERSION
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_CF_CLIENT_ID
      - BUILDKITE_PLUGIN_GOKAKASHI_SCAN_CF_CLIENT_SECRET
      - BUILDKITE_AGENT_META_DATA_PATH=/tmp/buildkite-agent/meta-data